### PR TITLE
Bug 1302264 - Add support for new-style gzip-compressed objects

### PR DESCRIPTION
**Pull request by whd**

### CODE REVIEW

**Comment by vitillo** [comment]
@maurodoglio r?

**Comment by whd** [comment]
@mreid-moz r?

**Comment by maurodoglio** [comment]
Do we really need those custom classes? What about something like this?

``` python
def unzip_stream(s):
    gzip.GzipFile(fileobj=StringIO.StringIO(s.read()))
```

if, fore some reason, we need a seekable object in output we can wrap it in another buffer

**Comment by whd** [comment]
`s.read()` will read the entire object into memory first before performing the gunzip, which I think is probably undesirable when we can stream it using the custom classes.

**Comment by whd** [comment]
And to be clear, this does not create a seekable file from the stream, it works around the fact that `GzipFile` internally uses `seek` because it assumes the `fileobj` is seekable.

**Comment by mreid-moz** [comment]
Looks good to me, r+

**Comment by mreid-moz** [comment]
Hmm... I was about to suggest incrementing the version in `setup.py` and pushing to PyPI, but it doesn't appear that the current version was pushed to PyPI.

@vitillo do you know why `1.1.0` wasn't pushed? was there a problem with it? The version was incremented with [this change](https://github.com/mozilla/telemetry-tools/commit/e019888629b51d468ae06625f08d1b0654bbd0a3).

**Comment by maurodoglio** [comment]
@whd yeah it's a tradeoff between performance and maintainability.

**Comment by whd** [comment]
@vitillo can you take a look regarding PyPI query above?

**Comment by vitillo** [comment]
There was no problem with it but the change does not affect `python_moztelemetry` since backtracking is disabled by default. 

That said, this library [should not exist](https://bugzilla.mozilla.org/show_bug.cgi?id=1290176) in the first place. The few things that python_moztelemetry needs should be moved there. Can we add the required functionality directly to python_moztelemetry?

**Comment by mreid-moz** [comment]
I think deprecating this library is a good idea, but I'd prefer to do it in a follow-up PR rather than in the context of this unrelated bug.

**Comment by vitillo** [comment]
I would rather press to merge this patch in moztelemetry once the few functions that moztelemetry needs have been ported there. It never seems to be a good time to this work so maybe having an important patch being blocked by it can help with re-prioritization. @maurodoglio what do you think? How long do you think it would take?

**Comment by maurodoglio** [comment]
telemetry-tools is used by moztelemetry in 3 different places:
- `unpack` is used [here](https://github.com/mozilla/python_moztelemetry/blob/50b0e22c05938c797adf8fc9ebe278d45348c433/moztelemetry/heka_message_parser.py#L11)
- `TelemetrySchema` is used [here](https://github.com/mozilla/python_moztelemetry/blob/50b0e22c05938c797adf8fc9ebe278d45348c433/moztelemetry/spark.py#L26)
- `s3u` is used [here](https://github.com/mozilla/python_moztelemetry/blob/50b0e22c05938c797adf8fc9ebe278d45348c433/moztelemetry/spark.py#L27)
Since both `TelemetrySchema` and `s3u` won't be necessary once [bug 1317294](https://bugzilla.mozilla.org/show_bug.cgi?id=1317294) is solved I propose to solve it first. Moving/Copying telemetry.utils.heka_message to moztelemetry will be quick and easy after that.

**Comment by maurodoglio** [comment]
moztelemetry doesn't depend on telemetry-tools anymore. See https://github.com/mozilla/python_moztelemetry/pull/100/files for details.

**Pull request closed without merging**
